### ISSUE TITLE
Promise sqlite 

### ISSUE THREAD

**Issue by Cheburashii** [Cheburashii/MyPMS#3]
Write promise decorators for sqlite methods:
 - run(query: string, values: any[]): Promise<SqlStatement>,
 - exec(query: string, values: any[]): Promise<SqlStatement>,
 - get(query: string, values: any[]): Promise<any>,
 - all(query: string, values: any[]): Promise<any[]>,
 - close(): Promise<Boolean>.

**Comment by dmitriy-shmilo** [comment]
at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_projects\JSTuts\MyPMS\test\connection.js:1:82)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at D:\_projects\JSTuts\MyPMS\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\_projects\JSTuts\MyPMS\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (D:\_projects\JSTuts\MyPMS\node_modules\mocha\lib\mocha.js:495:10)
    at Object.<anonymous> (D:\_projects\JSTuts\MyPMS\node_modules\mocha\bin\_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by Cheburashii** [comment]
Fixed
